### ISSUE TITLE
Error when running the cifar10 code

### ISSUE THREAD

**Issue by wengzejia1** [uds-lsv/evaluating-logit-pairing-methods#1]
When I run the mnist_cifar10 code, I set the dataset as "cifar10" in train.sh. Other parameters are kept as default. There happened an error that I could not solve it. The error information is as bellow:

tensorflow.python.framework.errors_impl.InvalidArgumentError: The node ConstantFolding/Optimizer/gradients/Model/Losses/Regularizers/Clean-Logit-Pairing/mean_squared_error/div_grad/BroadcastGradientArgs-folded-1' has inputs from different frames. The input 'Model/PGD-Attacker/while/conv-block-2/batch-norm-conv8/cond_3/Merge' is in frame 'Model/PGD-Attacker/while/while_context'. The input 'Model/PGD-Attacker/Logits/conv-block-3/batch-norm-conv18/cond_3/Merge' is in frame ''. 

Can you help me to solve the problem?

Tool Version I use: Tensorflow 1.8.0, Python 3.6.8, Pytorch 1.0.1, cleverhans 3.0.1

**Comment by max-andr** [comment]
Hi,

We think it might be because we might have actually used an older version of Cleverhans in our experiments. 
Could you try to run our scripts with some previous version of Cleverhans, e.g. with v2.1?

Please let us know whether it works, so we can update the "Requirements" if needed.

Thanks.

**Comment by max-andr** [comment]
I'm closing this issue for the moment.

Feel free to reopen it once you have some updates regarding the Cleverhans version.
