### ISSUE TITLE
code for visualizing the loss landscape

### ISSUE THREAD

**Issue by selous123** [uds-lsv/evaluating-logit-pairing-methods#2]
We are very interesting in your loss landscape drawing.

can you share code about the drawing? or any paper you refer to ?

**Comment by max-andr** [comment]
Hi,

thanks for the interest in our paper!
It should be just the standard one from matplotlib:
https://matplotlib.org/3.1.0/gallery/mplot3d/surface3d.html

**Comment by selous123** [comment]
Ok, thanks your replying!
